"use client";

import { useApp } from "@/context/AppContext";

function printPO(listing: any, clientUser: any, vendorUser: any) {
  const w = window.open('', '_blank');
  if (!w) return;
  const html = `<!DOCTYPE html><html><head><title>Purchase Order ${listing.poNumber}</title>
<style>
  body { font-family: Arial, sans-serif; padding: 40px; color: #111; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  .header { display: flex; justify-content: space-between; border-bottom: 2px solid #16a34a; padding-bottom: 16px; margin-bottom: 24px; }
  .section { margin-bottom: 20px; }
  .section h3 { font-size: 13px; text-transform: uppercase; color: #16a34a; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin-bottom: 10px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  th { background: #f0fdf4; text-align: left; padding: 8px 12px; font-size: 12px; border: 1px solid #d1fae5; }
  td { padding: 8px 12px; font-size: 13px; border: 1px solid #e5e7eb; }
  .row { display: flex; gap: 40px; }
  .col { flex: 1; }
  .total { font-size: 16px; font-weight: bold; color: #16a34a; }
  .sig { margin-top: 60px; display: flex; justify-content: space-between; }
  .sig-box { border-top: 1px solid #111; width: 200px; text-align: center; padding-top: 8px; font-size: 12px; }
  .badge { display: inline-block; padding: 2px 10px; border-radius: 20px; font-size: 11px; font-weight: bold; background: #dcfce7; color: #15803d; }
</style></head><body>
<div class="header">
  <div>
    <h1>PURCHASE ORDER</h1>
    <p style="margin:0;color:#6b7280;font-size:13px;">WeConnect E-Waste Aggregator Platform</p>
  </div>
  <div style="text-align:right;">
    <p style="margin:0;font-weight:bold;font-size:16px;">${listing.poNumber}</p>
    <p style="margin:0;color:#6b7280;font-size:12px;">Issued: ${new Date(listing.poIssuedAt).toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' })}</p>
    <span class="badge">OFFICIAL DOCUMENT</span>
  </div>
</div>

<div class="row">
  <div class="col section">
    <h3>Buyer (Client)</h3>
    <p style="margin:4px 0;font-weight:bold;">${clientUser?.name || listing.userName || 'Client'}</p>
    <p style="margin:4px 0;font-size:13px;color:#374151;">Bank: ${clientUser?.bankDetails?.bankName || 'N/A'}</p>
    <p style="margin:4px 0;font-size:13px;color:#374151;">A/C: ${clientUser?.bankDetails?.accountNumber || 'N/A'}</p>
    <p style="margin:4px 0;font-size:13px;color:#374151;">IFSC: ${clientUser?.bankDetails?.ifscCode || 'N/A'}</p>
  </div>
  <div class="col section">
    <h3>Seller (Vendor)</h3>
    <p style="margin:4px 0;font-weight:bold;">${vendorUser?.name || listing.winnerVendorName || 'Vendor'}</p>
    <p style="margin:4px 0;font-size:13px;color:#374151;">Bank: ${vendorUser?.bankDetails?.bankName || 'N/A'}</p>
    <p style="margin:4px 0;font-size:13px;color:#374151;">A/C: ${vendorUser?.bankDetails?.accountNumber || 'N/A'}</p>
    <p style="margin:4px 0;font-size:13px;color:#374151;">IFSC: ${vendorUser?.bankDetails?.ifscCode || 'N/A'}</p>
  </div>
</div>

<div class="section">
  <h3>Material Details</h3>
  <table>
    <tr><th>Description</th><th>Category</th><th>Quantity (kg)</th><th>Location</th><th>Unit Price</th><th>Total</th></tr>
    <tr>
      <td>${listing.title}</td>
      <td>${listing.category}</td>
      <td>${listing.weight} kg</td>
      <td>${listing.location}</td>
      <td>₹${((listing.price || 0) / (listing.weight || 1)).toFixed(2)}/kg</td>
      <td>₹${(listing.price || 0).toLocaleString('en-IN')}</td>
    </tr>
  </table>
</div>

<div class="section">
  <h3>Commercial Summary</h3>
  <table>
    <tr><th>Component</th><th>Amount</th></tr>
    <tr><td>Material Value (received by Client from Vendor)</td><td>₹${(listing.price || 0).toLocaleString('en-IN')}</td></tr>
    <tr><td>WeConnect Commission (5% — paid by Vendor)</td><td>₹${Math.round((listing.price || 0) * 0.05).toLocaleString('en-IN')}</td></tr>
    <tr><td style="font-weight:bold;">Total Vendor Outflow</td><td style="font-weight:bold;">₹${Math.round((listing.price || 0) * 1.05).toLocaleString('en-IN')}</td></tr>
  </table>
</div>

<div class="row">
  <div class="col section">
    <h3>Payment Terms</h3>
    <p style="font-size:13px;">${listing.poPaymentTerms || 'As per agreement'}</p>
  </div>
  <div class="col section">
    <h3>Delivery Terms</h3>
    <p style="font-size:13px;">${listing.poDeliveryTerms || 'As per agreement'}</p>
  </div>
</div>

${listing.poPenaltyClause ? `<div class="section"><h3>Penalty Clause</h3><p style="font-size:13px;">${listing.poPenaltyClause}</p></div>` : ''}
${listing.poSpecialConditions ? `<div class="section"><h3>Special Conditions</h3><p style="font-size:13px;">${listing.poSpecialConditions}</p></div>` : ''}

<div class="sig">
  <div class="sig-box">Client Signature</div>
  <div class="sig-box">Vendor Signature</div>
  <div class="sig-box">WeConnect Authority</div>
</div>
<p style="text-align:center;color:#9ca3af;font-size:11px;margin-top:40px;">Generated by WeConnect E-Waste Aggregator Platform</p>
</body></html>`;
  w.document.write(html);
  w.document.close();
  w.print();
}

export default function ClientPurchaseOrderPage() {
  const { currentUser, listings, users } = useApp();

  if (!currentUser) return null;

  const myListings = listings.filter(
    l => l.userId === currentUser.id || l.userId === currentUser.companyId || l.userName === currentUser.name
  ).filter(l => l.poStatus && l.poStatus !== 'pending');

  const getPoStatusBadge = (status?: string) => {
    const map: Record<string, string> = {
      issued: 'bg-blue-100 text-blue-700',
      acknowledged: 'bg-green-100 text-green-700',
    };
    return map[status || ''] || 'bg-slate-100 text-slate-600';
  };

  const getEmdStatusBadge = (status?: string) => {
    const map: Record<string, string> = {
      not_required: 'bg-slate-100 text-slate-500',
      pending: 'bg-yellow-100 text-yellow-700',
      submitted: 'bg-blue-100 text-blue-700',
      verified: 'bg-green-100 text-green-700',
    };
    return map[status || 'not_required'] || 'bg-slate-100 text-slate-500';
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 px-4 sm:px-6 lg:px-8 py-6">
      <div>
        <h1 className="text-2xl font-black text-slate-900 dark:text-white">Purchase Orders</h1>
        <p className="text-sm text-slate-500 mt-1">Purchase orders issued for your e-waste disposal deals.</p>
      </div>

      {myListings.length === 0 ? (
        <div className="text-center py-20 text-slate-400">
          <span className="material-symbols-outlined text-5xl mb-3 block">description</span>
          <p className="font-bold">No purchase orders yet.</p>
          <p className="text-sm">Purchase orders will appear once a deal is finalized for your listings.</p>
        </div>
      ) : (
        <div className="space-y-5">
          {myListings.map(listing => {
            const vendorUser = users.find(u => u.companyId === listing.winnerVendorId || u.name === listing.winnerVendorName);
            const commission = Math.round((listing.price || 0) * 0.05);

            return (
              <div key={listing.id} className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
                {/* Header */}
                <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-slate-800">
                  <div>
                    <p className="font-black text-slate-900 dark:text-white">{listing.title}</p>
                    <p className="text-xs text-slate-500">{listing.id} · Winner: {listing.winnerVendorName}</p>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className={`px-3 py-1 rounded-full text-xs font-bold capitalize ${getPoStatusBadge(listing.poStatus)}`}>
                      PO {listing.poStatus}
                    </span>
                    {listing.emdStatus && listing.emdStatus !== 'not_required' && (
                      <span className={`px-3 py-1 rounded-full text-xs font-bold capitalize ${getEmdStatusBadge(listing.emdStatus)}`}>
                        EMD: {listing.emdStatus.replace('_', ' ')}
                      </span>
                    )}
                  </div>
                </div>

                {/* PO Details */}
                {listing.poNumber && (
                  <div className="px-6 py-4 bg-slate-50 dark:bg-slate-800/40">
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                      <div>
                        <p className="text-xs text-slate-500 uppercase font-bold">PO Number</p>
                        <p className="font-black text-slate-900 dark:text-white mt-0.5">{listing.poNumber}</p>
                      </div>
                      <div>
                        <p className="text-xs text-slate-500 uppercase font-bold">Issued On</p>
                        <p className="font-semibold text-slate-700 dark:text-slate-300 mt-0.5">
                          {listing.poIssuedAt ? new Date(listing.poIssuedAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'}
                        </p>
                      </div>
                      <div>
                        <p className="text-xs text-slate-500 uppercase font-bold">Payment Terms</p>
                        <p className="font-semibold text-slate-700 dark:text-slate-300 mt-0.5 text-xs">{listing.poPaymentTerms || '—'}</p>
                      </div>
                      <div>
                        <p className="text-xs text-slate-500 uppercase font-bold">Delivery Terms</p>
                        <p className="font-semibold text-slate-700 dark:text-slate-300 mt-0.5 text-xs">{listing.poDeliveryTerms || '—'}</p>
                      </div>
                    </div>
                  </div>
                )}

                {/* Deal Summary */}
                <div className="px-6 py-4 grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-3">
                    <p className="text-xs font-black text-slate-500 uppercase tracking-widest">What You Receive</p>
                    <div className="bg-green-50 dark:bg-green-900/20 rounded-xl p-4 space-y-2">
                      <div className="flex justify-between text-sm">
                        <span className="text-slate-600 dark:text-slate-400">Material Value</span>
                        <span className="font-black text-green-700 dark:text-green-400 text-lg">₹{(listing.price || 0).toLocaleString('en-IN')}</span>
                      </div>
                      <p className="text-xs text-slate-500">Vendor pays 5% commission separately to WeConnect. You receive the full bid amount.</p>
                    </div>

                    <div className="bg-slate-50 dark:bg-slate-800/50 rounded-xl p-3">
                      <p className="text-xs font-bold text-slate-500 uppercase mb-2">Your Bank Account</p>
                      <p className="text-sm font-bold text-slate-900 dark:text-white">{currentUser.bankDetails?.accountHolderName || currentUser.name}</p>
                      <p className="text-xs text-slate-600 dark:text-slate-400">{currentUser.bankDetails?.bankName} · {currentUser.bankDetails?.accountNumber}</p>
                      <p className="text-xs text-slate-500">IFSC: {currentUser.bankDetails?.ifscCode}</p>
                    </div>
                  </div>

                  <div className="space-y-3">
                    <p className="text-xs font-black text-slate-500 uppercase tracking-widest">Winning Vendor</p>
                    <div className="bg-slate-50 dark:bg-slate-800/50 rounded-xl p-4 space-y-2">
                      <p className="font-bold text-slate-900 dark:text-white">{listing.winnerVendorName}</p>
                      {listing.emdStatus && listing.emdStatus !== 'not_required' && (
                        <div className="pt-2 border-t border-slate-200 dark:border-slate-700">
                          <p className="text-xs text-slate-500">EMD Status: <span className={`font-bold ${listing.emdStatus === 'verified' ? 'text-green-600' : 'text-orange-600'}`}>{listing.emdStatus.replace('_', ' ').toUpperCase()}</span></p>
                          {listing.emdAmount && <p className="text-xs text-slate-500">EMD Amount: ₹{listing.emdAmount.toLocaleString('en-IN')}</p>}
                        </div>
                      )}
                    </div>

                    {listing.poStatus === 'acknowledged' && (
                      <div className="bg-green-50 dark:bg-green-900/20 rounded-xl p-3 text-sm text-green-700 dark:text-green-300">
                        <span className="material-symbols-outlined text-base align-middle mr-1">check_circle</span>
                        Vendor has acknowledged this Purchase Order.
                      </div>
                    )}
                  </div>
                </div>

                {/* Actions */}
                <div className="flex flex-wrap gap-3 px-6 pb-5">
                  {listing.poNumber && (
                    <button onClick={() => printPO(listing, currentUser, vendorUser)}
                      className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-xl text-sm font-bold transition-colors flex items-center gap-2">
                      <span className="material-symbols-outlined text-base">download</span>
                      Download PO
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
